export const IPC_CHANNELS = {
  connectionsList: 'canvabase:connections:list',
  connectionsCreate: 'canvabase:connections:create',
  connectionsUpdate: 'canvabase:connections:update',
  connectionsDelete: 'canvabase:connections:delete',
  connectionsTest: 'canvabase:connections:test',
  connectionsConnect: 'canvabase:connections:connect',
  connectionsDisconnect: 'canvabase:connections:disconnect',
  browserTables: 'canvabase:browser:tables',
  browserCapabilities: 'canvabase:browser:capabilities',
  browserDatabases: 'canvabase:browser:databases',
  browserViews: 'canvabase:browser:views',
  browserProcedures: 'canvabase:browser:procedures',
  browserTriggers: 'canvabase:browser:triggers',
  browserUsers: 'canvabase:browser:users',
  queryExecute: 'canvabase:query:execute',
  queryFetchChunk: 'canvabase:query:fetchChunk',
  queryCancel: 'canvabase:query:cancel',
  querySuggest: 'canvabase:query:suggest',
  querySavedList: 'canvabase:query:saved:list',
  querySavedSave: 'canvabase:query:saved:save',
  querySavedDelete: 'canvabase:query:saved:delete',
  dataSchema: 'canvabase:data:schema',
  dataOpenTable: 'canvabase:data:open',
  dataUpdateRow: 'canvabase:data:updateRow',
  dataInsertRow: 'canvabase:data:insertRow',
  dataDeleteRow: 'canvabase:data:deleteRow',
  designerGetTable: 'canvabase:designer:getTable',
  designerPreviewDdl: 'canvabase:designer:previewDdl',
  designerApply: 'canvabase:designer:apply',
  designerDrop: 'canvabase:designer:drop',
  erdGenerate: 'canvabase:erd:generate',
  erdExportImage: 'canvabase:erd:exportImage',
  transferExport: 'canvabase:transfer:export',
  transferImport: 'canvabase:transfer:import',
  transferBackupDatabase: 'canvabase:transfer:backupDatabase',
  transferRestore: 'canvabase:transfer:restore',
  transferProgress: 'canvabase:transfer:progress',
  health: 'canvabase:health:health',
  themeSet: 'canvabase:theme:set',
  windowSetOpacity: 'canvabase:window:setOpacity',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
